spring.datasource.url=jdbc:mysql://localhost:3306/carmanagementsystem?createIfDatabaseNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# This tells Hibernate to build missing tables
spring.jpa.hibernate.ddl-auto=validate

# This ensures Hibernate writes the correct MySQL 8 syntax
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# This prints the SQL to your console so you can actually see it working
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.mapper.accept-case-insensitive-enums=true